config/routes.rb
TwitterForZombies::Application.routes.draw do
  resources :zombies

end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  attr_accessible :age, :bio, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zombies }
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/new
  # GET /zombies/new.json
  def new
    @zombie = Zombie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/1/edit
  def edit
    @zombie = Zombie.find(params[:id])
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render json: @zombie, status: :created, location: @zombie }
      else
        format.html { render action: "new" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zombies/1
  # PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      if @zombie.update_attributes(params[:zombie])
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy

    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TwitterForZombies
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/zombies/_form.html.haml
= form_for(@zombie) do |f|
  - if @zombie.errors.any?
    #error_explanation
      %h2
        = pluralize(@zombie.errors.count, "error")
        prohibited this zombie from being saved:
      %ul
        - @zombie.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :bio
    %br/
    = f.text_area :bio
  .field
    = f.label :age
    %br/
    = f.number_field :age
  .actions
    = f.submit

app/views/zombies/edit.html.haml
%h1 Editing zombie
= render 'form'
= link_to 'Show', @zombie
|
\#{link_to 'Back', zombies_path}

app/views/zombies/index.html.haml
%h1 Listing zombies
%table
  %tr
    %th Name
    %th Bio
    %th Age
    %th
    %th
    %th
  - @zombies.each do |zombie|
    %tr
      %td= zombie.name
      %td= zombie.bio
      %td= zombie.age
      %td= link_to 'Show', zombie
      %td= link_to 'Edit', edit_zombie_path(zombie)
      %td= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Zombie', new_zombie_path

app/views/zombies/new.html.haml
%h1 New zombie
= render 'form'
= link_to 'Back', zombies_path

app/views/zombies/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @zombie.name
%p
  %b Bio:
  = @zombie.bio
%p
  %b Age:
  = @zombie.age
= link_to 'Edit', edit_zombie_path(@zombie)
|
\#{link_to 'Back', zombies_path}